apiVersion: apps/v1
kind: Deployment
metadata:
  name: cancel
  labels:
    app: cancel
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cancel
  template:
    metadata:
      labels:
        app: cancel
    spec:
      containers:
        - name: cancel
          image: cloth.azurecr.io/cancell
          ports:
            - containerPort: 8080